version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: katalonstudio/katalon:8.1.0
    steps:
      - checkout
      - run: 
          name: Execute Katalon Studio
          command: cd Tests && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -exec
