<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de identificacin</name>
   <tag></tag>
   <elementGuidId>7924eb29-2d8d-4aa2-b5e0-38089d817f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#94666663</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='94666663']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ValidateDocumentIDNumber,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9OGZjODBiOTU1ZGUyYWMzNGI0NGQ0MDNhNzc2YjAwNTBhMjE1NGRlOGVlMmUyNDUwOTk2MWVkODAyY2M5NDRiNzU1YTg5NGJhZWVlMTMyMzdjMGM3Y2FkOTAwZTY4YzI2ZDY3ZDllNDFlMThlZDE0YjUwNDY0NmNmZmQwN2FiMGVmMzk0MjJkYzQ4YTc4MGM5NzA2Nzc1NTFlYjg5NmE4ODBkZDEzYTJhMWFiNzkxYTA2N2RjODY1ODM3NzZlZGU5ODlhM2FmYTA5ZGM3MmNkZjc3ZWRlMmRkZjUzMmIxNmZjNWU5M2Q5MTBiZTRjOThlZWUxMTJlNmVmN2U5NDU5ZmYxZDc2MjFlYjBlYTY2ZTY4NDQ5M2MxNGU3ZDA5OGI2YTNhMmEwMjk2ZWY0YTVjYmFhMDg1ZjdkMDY1MDM0NTQwNjY5MzVmOWQ0NTgyMTg1ZmUyZDU3MDYzNmUzYTQzZjU1NzE2ZGFlNjA2ZDkzY2U2MzlhY2ZhYWMyM2NmYjY5ZTg4OWE0YWE0YzE2NDJhMTk4Yzc4ODg3MDQwMTlmYTM0MWI4ZmJjM2MzMWI2ZGFkMDEwZjlhNzUzMTc3ZDg4YQ%3D%3D*&quot;,{},{&quot;FigurePageName&quot;:&quot;pyWorkPage.CurrentBenefeciary&quot;}],&quot;pyWorkPage&quot;]]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>94666663</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>a31330791c9ed688fa65aeb33fff6a443f3e696d420_4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>pyWorkPage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pCurrentBenefeciary$pIdentityNumber</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pCurrentBenefeciary$pIdentityNumberError</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;94666663&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='94666663']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div[2]/div/div[4]/div/div/div/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span/input</value>
   </webElementXpaths>
</WebElementEntity>
