<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Actividad econmica de la empresa_pi pi-ca_183de0</name>
   <tag></tag>
   <elementGuidId>f3584f85-afcf-489e-90d3-78f1571d14f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-item.content-field.item-9.remove-left-spacing.remove-right-spacing.flex.required > div.field-item.dataValueWrite > div.combo-box > button[type=&quot;button&quot;] > i.pi.pi-caret-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div[9]/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi pi-caret-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/div[@id=&quot;RULE_KEY&quot;]/div[@id=&quot;EXPAND-OUTERFRAME&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-field item-9 remove-left-spacing remove-right-spacing flex required&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/div[@class=&quot;combo-box&quot;]/button[1]/i[@class=&quot;pi pi-caret-down&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div[9]/div/div/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/button/i</value>
   </webElementXpaths>
</WebElementEntity>
