<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione una opcinALTA VERAPAZBAJA_985038_1</name>
   <tag></tag>
   <elementGuidId>5fca8aa1-bf93-483c-ab90-741cd3cdc002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#858426f7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='858426f7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;setValue&quot;, [[&quot;pyWorkPage.pyWorkParty(Customer).MunicipalityDepartmentName&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;], [&quot;pyWorkPage.pyWorkParty(Customer).MunicipalityDepartmentID&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;]]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;MapDataSourceProperty,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9OGRiNDEzMTlhMGIwYzIxZTlmYjdjODc4NTU2MDRmMzM0ZmNkOWI1NDZjMWM0YTE0YjQ0MzUzZDkzNzc2MzA0N2U3NzZiMWYyNTMxODBjMWY5MGVjMWNlNjdlMTc3YjAxM2UzY2JiOTU2YzI0YmE0MmZmYzkyMzhlZTkxNWUwYTE4Mjk3YjU5OWU5NDM1MDkxYmI1ZmUwYzg5Yzc4NzMwMmEyNmNkMzViNDc3MDVlNDUzNjI4MzEyZDZhOGE4MWJlNTEwNjVjNmY2YmI4ODQ3MjdkNzQ4YTI3NDZlOTQxZWM4ZjY4NGJiYTM1MDUzZjc5MzNiODlhYjE3YmMzN2VhYzYyZjkwZWY3NzdiNzA3YTdlODg0MGM3N2VkZjFkMDYwOTI2YmQxNDA2MWQ4NmQ0OWMxMTE0ZDcxMzFmNTE2NzFmOGYzYWFkMmJhZTYyMzQ0MjYyZDZlYzI3YTA5MWVhNjRhMGVmZDQ5M2JjNGRmOGQ1MDQ1NWZiYTIzOGE3ZmMxNmJhYzIyMjg5ODVhOGE5ZTgyOGNiZTE3NzFkMDYxNGJiZDA1MDMwNGEyYmZkNDE0NzYzZWMyMWVmMTUyM2Y5Nw%3D%3D*&quot;,{},{&quot;propertyDescription&quot;:&quot;EmittedDepartament&quot;}],&quot;pyWorkPage.pyWorkParty(Customer)&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PpyWorkPage$ppyWorkParty$gCustomer$pEmittedDepartmentName&quot;,&quot;!=&quot;,&quot;&quot;,&quot;false&quot;]]]]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>858426f7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bac_mobile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyWorkParty$gCustomer$pEmittedDepartmentName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>5aa6ff636284df2b927e4008aaa84d489724cd3e_34</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>pyWorkPage.pyWorkParty(Customer)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellid</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyWorkParty$gCustomer$pEmittedDepartmentNameError</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

  Seleccione una opción

ALTA VERAPAZBAJA VERAPAZCHIMALTENANGOCHIQUIMULAESCUINTLAGuatemalaHUEHUETENANGOIZABALJALAPAJUTIAPAPETENEL PROGRESOQUICHEQUETZALTENANGORETALHULEUSACATEPEQUEZSAN MARCOSSOLOLASANTA ROSASUCHITEPEQUEZTOTONICAPANZACAPA

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;858426f7&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='858426f7']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[6]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento de emisión de identificación'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de vencimiento de identificación'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio de emisión de identificación'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de contacto'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
