<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione una opcinALTA VERAPAZBAJA_985038_1_2_3</name>
   <tag></tag>
   <elementGuidId>36774bb0-2427-441b-b8aa-5232af190467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4ac70ed8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='4ac70ed8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;setValue&quot;, [[&quot;pyWorkPage.pyWorkParty(Customer).City&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;], [&quot;pyWorkPage.pyWorkParty(Customer).District&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;]]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;MapDataSourceProperty,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9OGRiNDEzMTlhMGIwYzIxZTlmYjdjODc4NTU2MDRmMzM0ZmNkOWI1NDZjMWM0YTE0YjQ0MzUzZDkzNzc2MzA0N2U3NzZiMWYyNTMxODBjMWY5MGVjMWNlNjdlMTc3YjAxM2UzY2JiOTU2YzI0YmE0MmZmYzkyMzhlZTkxNWUwYTFhYjA4ZWRhNjM5M2UxNTE2NjI0N2FhNjMxMDRlYjNhNzFlNDJhZWVkNmMzMjJkNjU4ZjZmNTJiYmQyNzIwNWVmNDQ3MGQ3YjE5MTQ3ZjliNGQxNWEwYjAwMGVkOTdjNTUzYjI3YjhjODg1NWFkNTc5NjUwZDk1YTk2YzA3NDdkMjc0ODdhZDY5MTA3MTg2OTcxNDgwY2E5MGNhYWYyODA5ODIyYzE5NTNiNjgzZGU2YTY3MGI0NDJmMzcyYjQzNGM5ZmY2MGY5YWZjY2NmYzcyYjY1ZGIzYTg0OWZiNjAwY2Q4YmJmMzdhYWIxYTBlNjNiNDUzNmFiMDhjYmFkMjYwYzZjOGU2NGVlOTI2YjNhODU0NjcxM2M1YjlhNGVhOWI2NjBmYTk3ZWIwMjg2NDlhYzFkMWI1OTRhM2MxNWQxYw%3D%3D*&quot;,{},{&quot;propertyDescription&quot;:&quot;WorkAddressProvince&quot;}],&quot;pyWorkPage.pyWorkParty(Customer)&quot;]]]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4ac70ed8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bac_mobile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyWorkParty$gCustomer$pCompanyAddressPage$pProvinceBasedOnCountry</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>ea75dbf867fea21d60e8fbec5d5dc53941577a88_10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>pyWorkPage.pyWorkParty(Customer)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellid</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$ppyWorkParty$gCustomer$pCompanyAddressPage$pProvinceBasedOnCountryError</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

  Seleccione una opción

ALTA VERAPAZBAJA VERAPAZCHIMALTENANGOCHIQUIMULAESCUINTLAGuatemalaHUEHUETENANGOIZABALJALAPAJUTIAPAPETENEL PROGRESOQUICHEQUETZALTENANGORETALHULEUSACATEPEQUEZSAN MARCOSSOLOLASANTA ROSASUCHITEPEQUEZTOTONICAPANZACAPA

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4ac70ed8&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='4ac70ed8']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento de la empresa'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guatemala'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipio de la empresa'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirección de la empresa'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
